apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: reviews
spec:
  hosts:
    - reviews
  http:
  - route:
    - destination:
        host: reviews
        subset: {{ .Values.virtualService.subset1 }}
      weight: {{ .Values.virtualService.weight1 }}
    - destination:
        host: reviews
        subset: {{ .Values.virtualService.subset2 }}
      weight: {{ .Values.virtualService.weight2 }}
